config/routes.rb
Rails.application.routes.draw do
  get    '/login', to: 'user_sessions#new'
  post   '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'

  resources :groups, only: [:new, :create, :show] do
    resources :houseworks, only: %i[new create edit update index]
  end
  resources :users, only: %i[new create]
  resources :calculations, only: %i[new create]
  resources :singleshots, only: %i[new create edit update show] do
    member do
      get 'your_burden'
      patch 'your_burden_update'
      get 'partner_burden'
      patch 'partner_burden_update'
    end
  end
  resources :invites
  root 'static_pages#home'
end

app/models/housework.rb
class Housework < ApplicationRecord
  validates :name, presence: true
  validates :score, presence: true
  belongs_to :group
  has_many :calculations
  has_one :default
end

app/controllers/houseworks_controller.rb
class HouseworksController < ApplicationController

  def index
    insert_setup
    @houseworks = Housework.includes(:group).where(group_id: @group.id)
  end

  def new
  	@housework = Housework.new
    insert_setup
  end

  def create
    array =  params[:housework][:houseworks]
    if Housework.insert_all(array)
      redirect_to group_path(current_user.group_users), success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def edit
    insert_setup
    @housework = Housework.find(params[:id])
  end

  def update
    insert_setup
    @housework = Housework.find(params[:id])

    if @housework.update(edit_housework_params)
      redirect_to group_houseworks_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :edit
    end
  end

  private

  def housework_params
  	params.require(:housework).permit(houseworks: [%w(name score created_at updated_at)])
  end

  def edit_housework_params
    params.permit(:name, :score)
  end
end

app/views/houseworks/_form.html.slim
= form_with model:[group,housework] , local: true do |f|
  .form-group
    = f.text_field '[houseworks][][name]', class: 'form-control', value: (Housework.human_attribute_name(:bath_cleaning)), readonly: true
    = f.number_field '[houseworks][][score]', class: 'form-control', min: 0, max: 10, value:2
    = f.hidden_field 'houseworks[][group_id]', value: group.id
    = f.hidden_field 'houseworks[][created_at]', value: time
    = f.hidden_field 'houseworks[][updated_at]', value: time

    = f.text_field '[houseworks][][name]', class: 'form-control', value: (Housework.human_attribute_name(:washing_up)), readonly: true
    = f.number_field '[houseworks][][score]', class: 'form-control', min: 0, max: 10, value:2
    = f.hidden_field 'houseworks[][group_id]', value: group.id
    = f.hidden_field 'houseworks[][created_at]', value: time
    = f.hidden_field 'houseworks[][updated_at]', value: time

    = f.text_field '[houseworks][][name]', class: 'form-control', value: (Housework.human_attribute_name(:washing)), readonly: true
    = f.number_field '[houseworks][][score]', class: 'form-control', min: 0, max: 10, value:2
    = f.hidden_field 'houseworks[][group_id]', value: group.id
    = f.hidden_field 'houseworks[][created_at]', value: time
    = f.hidden_field 'houseworks[][updated_at]', value: time

    = f.text_field '[houseworks][][name]', class: 'form-control', value: (Housework.human_attribute_name(:vacuum_cleaner)), readonly: true
    = f.number_field '[houseworks][][score]', class: 'form-control', min: 0, max: 10, value:2
    = f.hidden_field 'houseworks[][group_id]', value: group.id
    = f.hidden_field 'houseworks[][created_at]', value: time
    = f.hidden_field 'houseworks[][updated_at]', value: time

    = f.text_field '[houseworks][][name]', class: 'form-control', value: (Housework.human_attribute_name(:cooking)), readonly: true
    = f.number_field '[houseworks][][score]', class: 'form-control', min: 0, max: 10, value:2
    = f.hidden_field 'houseworks[][group_id]', value: group.id
    = f.hidden_field 'houseworks[][created_at]', value: time
    = f.hidden_field 'houseworks[][updated_at]', value: time
  = f.submit "ポイントを付与する", class: 'btn btn-primary'

app/views/houseworks/edit.html.slim
= render 'shared/flash_message'
.edit-container
  .edit-row
    h1 = (t 'houseworks.edit.edit_point')
  .form-block
    p = (t 'houseworks.edit.can_edit_point')
    /= form_with model: @housework, method: :patch , local: true do |f|
    = form_with(url: group_housework_path(@group, @housework), method: :patch, local: true) do |f|
      .form-group
         = f.text_field :name, class: 'form-control', value: @housework.name, readonly: true
         = f.number_field :score, class: 'form-control', min: 0, max: 10, value: @housework.score
      = f.submit (t 'houseworks.edit.submit'), class: 'btn btn-primary'

app/views/houseworks/index.html.slim
= render 'shared/flash_message'
.view-container
  .housework-top
    h1= (t 'houseworks.index.register')
  .housework-block
    - @houseworks.each do |housework|
      .block-top
        .name-block
          p = "現在の「" + housework.name + "」のポイント"
        .score-block
          p = housework.score
        = link_to (t 'houseworks.index.edit'), edit_group_housework_path(@group, housework), class: 'btn.btn-outline-secondary'
  .mypage-link
    = link_to 'マイページに戻る', group_path(@group)

app/views/houseworks/new.html.slim
= render 'shared/flash_message'
.container
  .row
    .col-lg-8.offset-lg-2
      h1= (t 'houseworks.new.register')
      p = (t 'houseworks.new.tell_burden')
      = render 'form', { housework: @housework, group: @group, time: @time }