config/routes.rb
Rails.application.routes.draw do
  get    '/login', to: 'user_sessions#new'
  post   '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'

  resources :groups, only: [:new, :create, :show] do
    resources :houseworks, only: %i[new create edit update index]
  end
  resources :users, only: %i[new create]
  resources :calculations, only: %i[new create]
  resources :singleshots, only: %i[new create edit update show] do
    member do
      get 'your_burden'
      patch 'your_burden_update'
      get 'partner_burden'
      patch 'partner_burden_update'
    end
  end
  resources :invites
  root 'static_pages#home'
end

app/models/group.rb
class Group < ApplicationRecord

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: true }

  has_many :group_users
  has_many :users, through: :group_users
  has_many :houseworks

  has_many :invites
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
  end

  def create
    @user = current_user
    @group = @user.groups.build(group_params)
     if @user.save
       redirect_to new_invite_path, success: "メンバーを招待しましょう"
     else
       flash.now[:danger] = t('.fail')
       render :new
     end
  end

  def show
    @date = GroupUser.find_by(user_id: current_user.id)
    @group = Group.find_by(id: @date.group_id)
    identify_partner
    percentage
    unless @yours.blank?
      @sum = [[current_user.name, @yours], [@partner_name.name, @partners]]
    end
  end


  private

  def group_params
  	params.require(:group).permit(:name)
  end

  def identify_partner
    group_number = current_user.group_users[0].group_id
    array = GroupUser.where(group_id: group_number)
    @partner_array = array.where.not(user_id: current_user.id)

    unless @partner_array.blank?
      @partner = @partner_array[0].user_id
      @partner_name = User.find_by(id: @partner)
    end
  end

  def percentage
    unless @partner.blank?
      @week = Time.current.all_week
      your_sums = Calculation.where(user_id: current_user.id, created_at: @week).sum(:sum)
      partner_sums = Calculation.where(user_id: @partner, created_at: @week).sum(:sum)
      group_sum = your_sums + partner_sums
      @yours = your_sums/group_sum.to_f*100
      @partners = partner_sums/group_sum.to_f*100
    end
  end
end

app/views/groups/_form.html.slim
= form_with model: group, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  = f.submit (t 'groups.new.make'), class: 'btn btn-primary'

app/views/groups/new.html.slim
= render 'shared/flash_message'
.container
  .row
    .col-lg-8.offset-lg-2
      h1= (t 'groups.new.title')
      = render 'form', { group: @group }

app/views/groups/show.html.slim
= render 'shared/flash_message'
.top-wrapper
  .weekly-percentage
    h2 = (t 'groups.show.today_housework')

  .pie-chart
    - if @sum.blank?
      .no-date
        = "家事データがありません"
    - elsif @sum[0].include?(current_user.name)
      = pie_chart @sum, colors: ["#ff7f50", "#87ceeb"], loading: "計算中...", library: {legend: { position: "top", backgroundColor: "#ffffea"}}
    - else
      .no-date
        = "家事データがありません"

  .select-contents
    .today-housework
      = link_to (t 'groups.show.input_housework'), new_calculation_path, class: 'btn btn-outline-danger'
    .show-detail
      = link_to (t 'groups.show.show_detail'), root_path, class: 'btn btn-outline-danger'
    .show-detail
      = link_to '家事ポイントを編集', group_houseworks_path(@group), class: 'btn btn-outline-danger'



/  .pie-chart
    - if @sum[0].include?(current_user.name)
      = pie_chart @sum, colors: ["#ff7f50", "#87ceeb"], loading: "計算中...", library: {legend: { position: "top", backgroundColor: "#ffffea"}}
    - else
      .no-date
        = "家事データがありません"