config/routes.rb
Rails.application.routes.draw do
  get    '/login', to: 'user_sessions#new'
  post   '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'

  resources :groups, only: [:new, :create, :show] do
    resources :houseworks, only: %i[new create edit update index]
  end
  resources :users, only: %i[new create]
  resources :calculations, only: %i[new create]
  resources :singleshots, only: %i[new create edit update show] do
    member do
      get 'your_burden'
      patch 'your_burden_update'
      get 'partner_burden'
      patch 'partner_burden_update'
    end
  end
  resources :invites
  root 'static_pages#home'
end

app/views/shared/_flash_message.html.slim
- flash.each do |message_type, message|
  div class=("alert alert-#{message_type}") = message

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-md.navbar-dark.bg-warning.shadow-sm
  .container
    /#a.navbar-brand[href="#"]
    = link_to "kajino", root_path, class: 'navbar-brand'

app/views/shared/_login_header.html.slim
nav.navbar.navbar-expand-md.navbar-dark.bg-warning.shadow-sm
  .container
    .container-left
      = link_to "kajino", root_path, class: 'navbar-brand'
    .container-center
      = link_to "ログアウト", logout_path, class: 'navbar-brand', method: :delete
      = link_to "グループを作成する", new_group_path, class: 'navbar-brand'
      = link_to current_user.name, root_path, class: 'navbar-brand'

app/views/shared/_validate_error.html.slim
- if user.errors.any?
  .alert
    ul
      - user.errors.full_messages.each do |message|
        li= message