config/routes.rb
Rails.application.routes.draw do
  get    '/login', to: 'user_sessions#new'
  post   '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'

  resources :groups, only: [:new, :create, :show] do
    resources :houseworks, only: %i[new create edit update index]
  end
  resources :users, only: %i[new create]
  resources :calculations, only: %i[new create]
  resources :singleshots, only: %i[new create edit update show] do
    member do
      get 'your_burden'
      patch 'your_burden_update'
      get 'partner_burden'
      patch 'partner_burden_update'
    end
  end
  resources :invites
  root 'static_pages#home'
end

app/models/singleshot.rb
class Singleshot < ApplicationRecord
  validates :your_name, presence: true
  validates :partner_name, presence: true
end

app/controllers/singleshots_controller.rb
class SingleshotsController < ApplicationController
  skip_before_action :require_login

  def new
    @singleshot = Singleshot.new
  end

  def create
    @singleshot = Singleshot.create(name_params)
    if @singleshot.save
      redirect_to edit_singleshot_path(@singleshot), success: "残りあと3問です！"
    else
      flash.now[:danger] = "入力に不備があります"
      render :new
    end
  end

  def edit
    params_identification
  end

  def update
  	params_identification
    if @singleshot.update(name_params)
      redirect_to your_burden_singleshot_path(@singleshot), success: '残り2問です！'
    else
      flash.now[:danger] = "入力に不備があります"
      render :edit
    end
  end

  def show
    params_identification
    calculation_pie_chart
  end

  def your_burden
    params_identification
  end

  def your_burden_update
  	params_identification
    if @singleshot.update(singleshot_params)
      your_burden_calculation
      redirect_to partner_burden_singleshot_path(@singleshot), success: 'ラスト1問！'
    else
      flash.now[:danger] = "入力に不備があります"
      render :your_burden
    end
  end

  def partner_burden
    params_identification
  end

  def partner_burden_update
  	params_identification
    if @singleshot.update(singleshot_params)
      partner_burden_calculation
      redirect_to singleshot_path(@singleshot), success: '家事負担の割合を確認しましょう！'
    else
      flash.now[:danger] = "入力に不備があります"
      render :partner_burden
    end
  end


  private

  def name_params
    params.require(:singleshot).permit(:your_name, :partner_name, :cook_point, :dish_washing_point, :laundry_point, :bath_washing_point, :vacuum_point)
  end

  def singleshot_params
    params.permit(:your_name, :partner_name, :cook_point, :dish_washing_point, :laundry_point, :bath_washing_point, :vacuum_point, :your_cook, :your_dish_washing, :your_laundry, :your_bath_washing, :your_vacuum, :partner_cook, :partner_dish_washing, :partner_laundry, :partner_bath_washing, :partner_vacuum)
  end

  def params_identification
  	@singleshot = Singleshot.find(params[:id])
  end

  def your_burden_calculation
  	@your_cook          = @singleshot.your_cook * @singleshot.cook_point
    @your_dish_washing  = @singleshot.your_dish_washing * @singleshot.cook_point
    @your_laundry       = @singleshot.your_laundry * @singleshot.cook_point
    @your_bath_washing  = @singleshot.your_bath_washing * @singleshot.cook_point
    @your_vacuum        = @singleshot.your_vacuum * @singleshot.cook_point
    @all_sum            = @your_cook + @your_dish_washing + @your_laundry + @your_bath_washing + @your_vacuum
  	Singleshot.update(your_cook_sum: @your_cook, your_dish_washing_sum: @your_dish_washing,
  		your_laundry_sum: @your_laundry, your_bath_washing_sum: @your_bath_washing, your_vacuum_sum: @your_vacuum, your_sum: @all_sum )
  end

  def partner_burden_calculation
  	@partner_cook          = @singleshot.partner_cook * @singleshot.cook_point
    @partner_dish_washing  = @singleshot.partner_dish_washing * @singleshot.cook_point
    @partner_laundry       = @singleshot.partner_laundry * @singleshot.cook_point
    @partner_bath_washing  = @singleshot.partner_bath_washing * @singleshot.cook_point
    @partner_vacuum        = @singleshot.partner_vacuum * @singleshot.cook_point
    @all_sum               = @partner_cook + @partner_dish_washing + @partner_laundry + @partner_bath_washing + @partner_vacuum
  	Singleshot.update(partner_cook_sum: @partner_cook, partner_dish_washing_sum: @partner_dish_washing,
  		partner_laundry_sum: @partner_laundry, partner_bath_washing_sum: @partner_bath_washing, partner_vacuum_sum: @partner_vacuum, partner_sum: @all_sum )
  end

  def calculation_pie_chart
  	@sum = [[@singleshot.your_name, @singleshot.your_sum], [@singleshot.partner_name, @singleshot.partner_sum]]
    @cook_ration = [[@singleshot.your_name, @singleshot.your_cook_sum], [@singleshot.partner_name, @singleshot.partner_cook_sum]]
    @dish_washing_ration = [[@singleshot.your_name, @singleshot.your_dish_washing_sum], [@singleshot.partner_name, @singleshot.partner_dish_washing_sum]]
    @laundry_ration = [[@singleshot.your_name, @singleshot.your_laundry_sum], [@singleshot.partner_name, @singleshot.partner_laundry_sum]]
    @bath_washing_ration = [[@singleshot.your_name, @singleshot.your_bath_washing_sum], [@singleshot.partner_name, @singleshot.partner_bath_washing_sum]]
    @vacuum_ration = [[@singleshot.your_name, @singleshot.your_vacuum_sum], [@singleshot.partner_name, @singleshot.partner_vacuum_sum]]
  end

end

app/views/singleshots/edit.html.slim
= render 'shared/flash_message'
.edit_singleshot_form
  .edit_top_contents
    p = "家事の負担をポイント化しましょう(最大100pt)"
    = form_with model: @singleshot , local: true do |f|
      = f.label :お料理
      = f.number_field :cook_point, class: 'form-control', size: 30, min: 0, max: 100, value:20
      = f.label :お皿洗い
      = f.number_field :dish_washing_point, class: 'form-control', size: 30, min: 0, max: 100, value:20
      = f.label :お洗濯
      = f.number_field :laundry_point, class: 'form-control', size: 30, min: 0, max: 100, value:20
      = f.label :お風呂掃除
      = f.number_field :bath_washing_point, class: 'form-control', size: 30, min: 0, max: 100, value:20
      = f.label :掃除機かけ
      = f.number_field :vacuum_point, class: 'form-control', size: 30, min: 0, max: 100, value:20
      = f.submit "送信", class: 'btn btn-primary'

app/views/singleshots/new.html.slim
= render 'shared/flash_message'
.singleshot_form
  .top_contents
    p = "あなたとパートナーのニックネームは？"
    = form_with model: @singleshot , local: true do |f|
      = f.label :Your_name
      = f.text_field :your_name, class: 'form-control', size: 30
      = f.label :Partner_name
      = f.text_field :partner_name, class: 'form-control', size: 30
      = f.submit "送信", class: 'btn btn-primary'

app/views/singleshots/partner_burden.html.slim
= render 'shared/flash_message'
.count_singleshot_form
  .count_top_contents
    p = "#{@singleshot.partner_name}さんは1日何回家事をしますか？"
    = form_with url: partner_burden_update_singleshot_path(@singleshot), method: :patch , local: true do |f|
      = f.label :お料理
      = f.number_field :partner_cook, class: 'form-control', size: 30, min: 0, max: 10, value:1
      = f.label :お皿洗い
      = f.number_field :partner_dish_washing, class: 'form-control', size: 30, min: 0, max: 10, value:1
      = f.label :お洗濯
      = f.number_field :partner_laundry, class: 'form-control', size: 30, min: 0, max: 10, value:1
      = f.label :お風呂掃除
      = f.number_field :partner_bath_washing, class: 'form-control', size: 30, min: 0, max: 10, value:1
      = f.label :掃除機かけ
      = f.number_field :partner_vacuum, class: 'form-control', size: 30, min: 0, max: 10, value:1
      = f.submit "送信", class: 'btn btn-primary'

app/views/singleshots/show.html.slim
= render 'shared/flash_message'
.chart-top
  .chart-sum
    p = "全体の負担割合"
    = pie_chart @sum, colors: ["#ff7f50", "#87ceeb"], loading: "計算中...", library: {legend: { position: "top", backgroundColor: "#ffffea"}}
  .chart-cook
    p = "料理の負担割合"
    = pie_chart @cook_ration, colors: ["#ff7f50", "#87ceeb"], library: {backgroundColor: "#ffffea"}, loading: "計算中...", library: {legend: { position: "top" }}
    .form_part
      a.btn-square-pop href="https://shop.hikaritv.net/kurashito/article/cooking_appliances.html"  この家事の負担を減らす

  .chart-dish_washing
    p = "皿洗いの負担割合"
    = pie_chart @dish_washing_ration, colors: ["#ff7f50", "#87ceeb"], library: {backgroundColor: "#ffffea"}, loading: "計算中...", library: {legend: { position: "top" }}
    .form_part
      a.btn-square-pop href="https://www.biccamera.com/bc/i/topics/osusume_dishwasher/index.jsp"  この家事の負担を減らす

  .chart-laundry
    p = "洗濯の負担割合"
    = pie_chart @laundry_ration, colors: ["#ff7f50", "#87ceeb"], library: {backgroundColor: "#ffffea"}, loading: "計算中...", library: {legend: { position: "top" }}
    .form_part
      a.btn-square-pop href="https://www.biccamera.com/bc/i/topics/laundry/index.jsp"  この家事の負担を減らす

  .chart-bath_washing
    p = "お風呂掃除の負担割合"
    = pie_chart @bath_washing_ration, colors: ["#ff7f50", "#87ceeb"], library: {backgroundColor: "#ffffea"}, loading: "計算中...", library: {legend: { position: "top" }}
    .form_part
      a.btn-square-pop href="https://my-best.com/3980"  この家事の負担を減らす

  .chart-vacuum
    p = "掃除機かけの負担割合"
    = pie_chart @vacuum_ration, colors: ["#ff7f50", "#87ceeb"], library: {backgroundColor: "#ffffea"}, loading: "計算中...", library: {legend: { position: "top" }}
    .form_part
      a.btn-square-pop href="https://kakakumag.com/seikatsu-kaden/?id=11326"  この家事の負担を減らす

app/views/singleshots/your_burden.html.slim
= render 'shared/flash_message'
.count_singleshot_form
  .count_top_contents
    p = "#{@singleshot.your_name}さんは1日何回家事をしますか？"
    = form_with url: your_burden_update_singleshot_path(@singleshot), method: :patch , local: true do |f|
      = f.label :お料理
      = f.number_field :your_cook, class: 'form-control', size: 30, min: 0, max: 10, value:1
      = f.label :お皿洗い
      = f.number_field :your_dish_washing, class: 'form-control', size: 30, min: 0, max: 10, value:1
      = f.label :お洗濯
      = f.number_field :your_laundry, class: 'form-control', size: 30, min: 0, max: 10, value:1
      = f.label :お風呂掃除
      = f.number_field :your_bath_washing, class: 'form-control', size: 30, min: 0, max: 10, value:1
      = f.label :掃除機かけ
      = f.number_field :your_vacuum, class: 'form-control', size: 30, min: 0, max: 10, value:1
      = f.submit "送信", class: 'btn btn-primary'